package Vistas;

import Clases.Session;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

public class Main extends javax.swing.JFrame {
    
    public Main() {
        initComponents();
    }
    
    public Main(Session se) {
        initComponents();
        setLocationRelativeTo(null);
        session = se;
        lblUsuario.setText("USUARIO: "+session.getUsuario());
    }
    
    private Session session;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClientes = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnVender = new javax.swing.JButton();
        btnMarcas = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnProductos = new javax.swing.JMenuItem();
        mnMarcas = new javax.swing.JMenuItem();
        mnClientes = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnVentas = new javax.swing.JMenuItem();
        mnUsuarios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnInfVentas = new javax.swing.JMenuItem();
        mnInfProductos = new javax.swing.JMenuItem();
        mnInfClientes = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LP1 - Menu");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClientes.setBackground(new java.awt.Color(51, 51, 51));
        btnClientes.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jPanel1.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 190, 30));

        btnProductos.setBackground(new java.awt.Color(51, 51, 51));
        btnProductos.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnProductos.setText("Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        jPanel1.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 190, 30));

        btnVender.setBackground(new java.awt.Color(51, 51, 51));
        btnVender.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnVender.setForeground(new java.awt.Color(255, 255, 255));
        btnVender.setText("Vender");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });
        jPanel1.add(btnVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 190, 30));

        btnMarcas.setBackground(new java.awt.Color(51, 51, 51));
        btnMarcas.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnMarcas.setForeground(new java.awt.Color(255, 255, 255));
        btnMarcas.setText("Marcas");
        btnMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcasActionPerformed(evt);
            }
        });
        jPanel1.add(btnMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 190, 30));

        lblUsuario.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuario.setText("USUARIO: ");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 200, -1));

        jMenu1.setText("Archivo");

        mnProductos.setText("Productos");
        mnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnProductosActionPerformed(evt);
            }
        });
        jMenu1.add(mnProductos);

        mnMarcas.setText("Marcas");
        mnMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMarcasActionPerformed(evt);
            }
        });
        jMenu1.add(mnMarcas);

        mnClientes.setText("Clientes");
        mnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnClientesActionPerformed(evt);
            }
        });
        jMenu1.add(mnClientes);

        jMenuItem4.setText("POS");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);
        jMenu1.add(jSeparator2);

        mnVentas.setText("Ventas");
        mnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVentasActionPerformed(evt);
            }
        });
        jMenu1.add(mnVentas);

        mnUsuarios.setText("Usuarios");
        mnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(mnUsuarios);
        jMenu1.add(jSeparator1);

        mnSalir.setText("Salir");
        mnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Informes");

        mnInfVentas.setText("Ventas");
        mnInfVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnInfVentasActionPerformed(evt);
            }
        });
        jMenu2.add(mnInfVentas);

        mnInfProductos.setText("Productos");
        mnInfProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnInfProductosActionPerformed(evt);
            }
        });
        jMenu2.add(mnInfProductos);

        mnInfClientes.setText("Clientes");
        mnInfClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnInfClientesActionPerformed(evt);
            }
        });
        jMenu2.add(mnInfClientes);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("About");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnSalirActionPerformed

    private void mnMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMarcasActionPerformed
        new Marcas(session).setVisible(true);
    }//GEN-LAST:event_mnMarcasActionPerformed

    private void mnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnProductosActionPerformed
        new Productos(session).setVisible(true);
    }//GEN-LAST:event_mnProductosActionPerformed

    private void mnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnClientesActionPerformed
        new Clientes(session).setVisible(true);
    }//GEN-LAST:event_mnClientesActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new Ventas(session).setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void mnInfProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnInfProductosActionPerformed
        
        try {
            String ruta = System.getProperty("user.dir");
            JasperPrint jasperPrint;
            String reportDest = ruta + "/src/Reportes/Productos.jasper";
            jasperPrint = JasperFillManager.fillReport(reportDest, null, session.getCon().getConexion());
            JasperViewer jv = new JasperViewer(jasperPrint, false);
            jv.setTitle("Historico");
            jv.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_mnInfProductosActionPerformed

    private void mnInfClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnInfClientesActionPerformed
        try {
            String ruta = System.getProperty("user.dir");
            JasperPrint jasperPrint;
            String reportDest = ruta + "/src/Reportes/Clientes.jasper";
            jasperPrint = JasperFillManager.fillReport(reportDest, null, session.getCon().getConexion());
            JasperViewer jv = new JasperViewer(jasperPrint, false);
            jv.setTitle("Historico");
            jv.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnInfClientesActionPerformed

    private void mnInfVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnInfVentasActionPerformed
        new InfVentas(session).setVisible(true);
    }//GEN-LAST:event_mnInfVentasActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        new About().setVisible(true);
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        new About().setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        new Clientes(session).setVisible(true);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        new Productos(session).setVisible(true);
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        new Ventas(session).setVisible(true);
    }//GEN-LAST:event_btnVenderActionPerformed

    private void btnMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcasActionPerformed
        new Marcas(session).setVisible(true);
    }//GEN-LAST:event_btnMarcasActionPerformed

    private void mnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVentasActionPerformed
        new ListadoVentas(session).setVisible(true);
    }//GEN-LAST:event_mnVentasActionPerformed

    private void mnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUsuariosActionPerformed
        new Usuarios(session).setVisible(true);
    }//GEN-LAST:event_mnUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnMarcas;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnVender;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem mnClientes;
    private javax.swing.JMenuItem mnInfClientes;
    private javax.swing.JMenuItem mnInfProductos;
    private javax.swing.JMenuItem mnInfVentas;
    private javax.swing.JMenuItem mnMarcas;
    private javax.swing.JMenuItem mnProductos;
    private javax.swing.JMenuItem mnSalir;
    private javax.swing.JMenuItem mnUsuarios;
    private javax.swing.JMenuItem mnVentas;
    // End of variables declaration//GEN-END:variables
}
