package Vistas;

import Clases.Session;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Productos extends javax.swing.JFrame {

    public Productos() {
        initComponents();
    }

    private Session session;

    public Productos(Session session) {
        initComponents();
        setLocationRelativeTo(null);
        activar(true);
        this.session = session;
        cargarDatos("");
        cargarMarcas();
        cargarImpuestos();
    }

    private ArrayList<Integer> idMarcas;
    private ArrayList<Integer> idImpuestos;

    public void cargarMarcas() {
        idMarcas = new ArrayList();

        ResultSet esta = session.getCon().listar("SELECT * FROM marcas");
        Vector<String> cus = new Vector();
        try {
            while (esta.next()) {
                cus.add(esta.getString("nombreMarca"));
                idMarcas.add(esta.getInt("idMarca"));
            }
        } catch (SQLException ex) {
            //Log.log(ex, this);
        }
        DefaultComboBoxModel mdl = new DefaultComboBoxModel(cus);
        cmbMarca.setModel(mdl);
    }
    
    public void cargarImpuestos() {
        idImpuestos = new ArrayList();

        ResultSet esta = session.getCon().listar("SELECT * FROM impuestos");
        Vector<String> cus = new Vector();
        try {
            while (esta.next()) {
                cus.add(esta.getString("nombreImpuesto"));
                idImpuestos.add(esta.getInt("idImpuesto"));
            }
        } catch (SQLException ex) {
            //Log.log(ex, this);
        }
        DefaultComboBoxModel mdl = new DefaultComboBoxModel(cus);
        cmbImpuestos.setModel(mdl);
    }

    private void cargarDatos(String val) {
        String sentencia = "SELECT * FROM productos WHERE nombreProducto LIKE '%" + val + "%'";
        ResultSet datos = session.getCon().listar(sentencia);
        String titulos[] = {"Id", "Descripción", "Existencia", "Precio"};
        DefaultTableModel m;
        m = new DefaultTableModel(null, titulos) {
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        String fila[] = new String[4];
        try {
            while (datos.next()) {
                fila[0] = datos.getString("idProducto");
                fila[1] = datos.getString("nombreProducto");
                fila[2] = datos.getInt("existencia")+"";
                fila[3] = datos.getInt("precio")+"";
                m.addRow(fila);
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        tblProductos.setModel(m);
    }

    private void activar(boolean a) {
        btnNuevo.setEnabled(a);
        btnModificar.setEnabled(a);
        btnGuardar.setEnabled(!a);
        btnCancelar.setEnabled(!a);
        btnEliminar.setEnabled(a);
        txtIdProducto.setEditable(!a);
        txtProducto.setEditable(!a);
        txtCodigo.setEditable(!a);
        txtExistencia.setEditable(!a);
        txtPrecio.setEditable(!a);
        txtBusqueda.setEditable(a);
        cmbImpuestos.setEnabled(!a);
        cmbMarca.setEnabled(!a);
    }

    private void limpiar() {
        txtProducto.setText("");
        txtCodigo.setText("");
        txtExistencia.setText("");
        txtPrecio.setText("");
        txtIdProducto.setText("");
        txtBusqueda.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        txtBusqueda = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtProducto = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JFormattedTextField();
        txtExistencia = new javax.swing.JFormattedTextField();
        cmbMarca = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cmbImpuestos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LP1 - Productos");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BUSCAR");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtIdProducto.setBackground(new java.awt.Color(0, 102, 102));
        txtIdProducto.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtIdProducto.setForeground(new java.awt.Color(255, 255, 255));
        txtIdProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 130, 30));

        btnGuardar.setBackground(new java.awt.Color(51, 51, 51));
        btnGuardar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 90, 30));

        btnNuevo.setBackground(new java.awt.Color(51, 51, 51));
        btnNuevo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 90, 30));

        btnCancelar.setBackground(new java.awt.Color(51, 51, 51));
        btnCancelar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 90, 30));

        btnModificar.setBackground(new java.awt.Color(51, 51, 51));
        btnModificar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 90, 30));

        btnEliminar.setBackground(new java.awt.Color(51, 51, 51));
        btnEliminar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 90, 30));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 580, 250));

        txtBusqueda.setBackground(new java.awt.Color(0, 102, 102));
        txtBusqueda.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        txtBusqueda.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });
        jPanel1.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 200, 30));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("EXISTENCIA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("IMPUESTO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NOMBRE PRODUCTO");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CODIGO");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PRECIO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        txtCodigo.setBackground(new java.awt.Color(0, 102, 102));
        txtCodigo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 380, 30));

        txtProducto.setBackground(new java.awt.Color(0, 102, 102));
        txtProducto.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtProducto.setForeground(new java.awt.Color(255, 255, 255));
        txtProducto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 380, 30));

        txtPrecio.setBackground(new java.awt.Color(0, 102, 102));
        txtPrecio.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtPrecio.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 160, 30));

        txtExistencia.setBackground(new java.awt.Color(0, 102, 102));
        txtExistencia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtExistencia.setForeground(new java.awt.Color(255, 255, 255));
        txtExistencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jPanel1.add(txtExistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 130, 30));

        cmbMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 380, 40));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("MARCA");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        cmbImpuestos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbImpuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 380, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String idProducto = txtIdProducto.getText().trim();
        String nombreProducto = txtProducto.getText().trim();
        String codigo = txtCodigo.getText().trim();
        String precio = txtPrecio.getText().trim();
        int pre = 0;
        int exi = 0;
        try {
            pre = Integer.parseInt(precio.replace(".", ""));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Precio no valido");
            return;
        }
        String existencia = txtExistencia.getText().trim();
        try {
            exi = Integer.parseInt(existencia.replace(".", ""));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Existencia no valida");
            return;
        }
        if (nombreProducto.length() > 0) {
            int idMarca = idMarcas.get(cmbMarca.getSelectedIndex());
            int idImpuesto = idImpuestos.get(cmbImpuestos.getSelectedIndex());
            if (idProducto.length() > 0) {
                session.ejecutar("UPDATE productos SET nombreProducto='" + nombreProducto + "',codigo='" + codigo + "',precio='" + pre + "',existencia='" + exi + "',idMarca=" + idMarca + ",idImpuesto="+idImpuesto+" WHERE idProducto=" + idProducto);
            } else {
                session.ejecutar("INSERT INTO productos (nombreProducto,codigo,precio,existencia,idMarca,idImpuesto) VALUES ('" + nombreProducto + "','" + codigo + "','" + pre + "','" + exi + "'," + idMarca + ","+idImpuesto+")");
            }
            cargarDatos("");
            limpiar();
            activar(true);

        } else {
            JOptionPane.showMessageDialog(this, "Ingrese descripción de la marca");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        activar(false);
        limpiar();
        txtIdProducto.setEditable(false);
        txtProducto.requestFocus();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        activar(true);
        limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int row = tblProductos.getSelectedRow();
        if (row >= 0) {
            String idProducto = tblProductos.getValueAt(row, 0).toString();
            ResultSet pro = session.listar("SELECT p.*,nombreMarca,nombreImpuesto FROM productos p INNER JOIN marcas m ON m.idMarca=p.idMarca INNER JOIN impuestos im ON im.idImpuesto=p.idImpuesto WHERE idProducto=" + idProducto);
            try {
                if (pro.next()) {
                    txtIdProducto.setText(idProducto);
                    txtProducto.setText(pro.getString("nombreProducto"));
                    txtCodigo.setText(pro.getString("codigo"));
                    txtExistencia.setText(pro.getInt("existencia") + "");
                    txtPrecio.setText(pro.getInt("precio") + "");
                    cmbImpuestos.setSelectedItem(pro.getString("nombreImpuesto"));
                    cmbMarca.setSelectedItem(pro.getString("nombreMarca"));
                    txtIdProducto.setEditable(false);
                    txtProducto.requestFocus();
                    txtProducto.selectAll();
                    activar(false);
                }
            } catch (SQLException ex) {

            }

        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un registro para editar");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int row = tblProductos.getSelectedRow();
        if (row >= 0) {
            String idProducto = tblProductos.getValueAt(row, 0).toString();
            int op = JOptionPane.showConfirmDialog(this, "Eliminar el registro", "Eliminar", JOptionPane.YES_NO_OPTION);
            if (op == JOptionPane.YES_OPTION) {

                ResultSet uso = session.getCon().listar("SELECT * FROM ventas_det WHERE idProducto=" + idProducto);
                try {
                    if (!uso.next()) {
                        session.getCon().ejecutar("DELETE FROM productos WHERE idMarca=" + idProducto);
                    } else {
                        JOptionPane.showMessageDialog(this, "El registro esta en uso, no es posible eliminar", "Error", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                } catch (SQLException ex) {

                }
                cargarDatos("");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un registro para eliminar");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        cargarDatos(txtBusqueda.getText());
    }//GEN-LAST:event_txtBusquedaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cmbImpuestos;
    private javax.swing.JComboBox<String> cmbMarca;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtExistencia;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JFormattedTextField txtPrecio;
    private javax.swing.JTextField txtProducto;
    // End of variables declaration//GEN-END:variables
}
